### ISSUE TITLE
code-coverage  execa does not support Node.js 8.0.0+

### ISSUE THREAD

**Issue by shijiu1919zyx** [cypress-io/code-coverage#143]
my code is as follows
```js
module.exports = (on, config) => {
  on('file:preprocessor', cucumber());
  on('task', require('@cypress/code-coverage/task'));
  config.env.API_ENVENV = process.env.API_ENVENV;
  return config;
};
```
But got the following error
![ii](https://user-images.githubusercontent.com/57492108/75303007-72976400-587a-11ea-82f1-54e622a1b9e8.jpg)

**Comment by sherry007** [comment]
well, i've had this problem too before. You should check the version of your cypress, and upgrade it to the latest one

**Comment by jennifer-shehane** [comment]
@shijiu1919zyx What Node.js version are you using?

We encountered a bug for installing Cypress in the 4.0+ version of Cypress where we are inadvertently not supported Node 8.0.0-8.12.0. https://github.com/cypress-io/cypress/issues/6512 (this will be fixed in next release)

This looks to be the exact same issue with the `code-coverage` plugin. The `execa` dep of 4.0.0 for this plugin requires a minimum Node version of 10.0.0. 

@bahmutov I think we should roll back `execa` dep for this plugin. We should support the same Node version for our own plugins as we do for Cypress (aka 8.0.0), so roll back execa to 2.0.0

For now, you can upgrade to use Node version 10.0.0. I couldn't actually even find a previous version of this plugin that was ever using execa 2.0.0.
