### ISSUE TITLE
Dependencies need ^ in their semver

### ISSUE THREAD

**Issue by quisido** [cypress-io/code-coverage#540]
In order to merge Cypress coverage reports with other coverage reports, the [`istanbul-lib-coverage` module needs to be the same version](https://github.com/istanbuljs/nyc/issues/1226#issuecomment-554842393).

Cypress, however, hard-locks it at `3.0.0`, when other packages correctly use `^3.0.0`.

As a result, I'm currently seeing other packages use `3.2.0`, and I am unable to upgrade Cypress's dependency because of its exact semver.

Expected behavior: `yarn up -R istanbul-lib-coverage` should set all my dependencies to the same version
Current behaviorr: `yarn up -R istanbul-lib-coverage` sets all of my dependencies _except Cypress_ to the latest version

**Comment by c5-ericlin** [comment]
Agreed. I ended up adding this

```json
  "resolutions": {
    "istanbul-lib-coverage": "^3.2.0"
  },
```

to lock `istanbul-lib-coverage` to `^3.2.0` in my package.json after realizing the merging issue mentioned in these threads ([1](https://github.com/istanbuljs/nyc/issues/1302#issuecomment-1232992665), [2](https://github.com/istanbuljs/nyc/issues/1333)) had been fixed in `istanbul-lib-coverage 3.2.0`, but cypress was locking it to `3.0.0`.

\[1\]: https://github.com/istanbuljs/nyc/issues/1302#issuecomment-1232992665
\[2\]: https://github.com/istanbuljs/nyc/issues/1333
