### ISSUE TITLE
Instrumenting does not work for component tests in Cypress v10 without Babel

### ISSUE THREAD

**Issue by aln447** [cypress-io/code-coverage#615]
**Logs and screenshots**
```
   ⚠️ Could not find any coverage information in your application
            by looking at the window coverage object.
            Did you forget to instrument your application?
            See [code-coverage#instrument-your-application](https://github.com/cypress-io/code-coverage#instrument-your-application)
           `[@cypress/code-coverage]`
Cannot find coverage file [...]nyc_output/out.json
Skipping coverage report
```

**Versions**

- What is this plugin's version?
- **^3.10.0**
- What is Cypress version?
- **10.6.0**
- What is your operating system?
- **MacOs**
- What is the shell?
- **Happens regardless of the shell**
- What is the Node version?
- **14.17.2**
- What is the NPM version?
- **6.14.13**
- How do you instrument your application? Cypress [does not instrument web application code](https://github.com/cypress-io/code-coverage#instrument-your-application), so you need to do it yourself.
- **Followed both the guide in [here](https://github.com/cypress-io/code-coverage#instrument-your-application), [here](https://github.com/cypress-io/code-coverage#instrument-unit-tests) and [here](https://github.com/cypress-io/code-coverage#alternative-for-unit-tests)**
- When running tests, if you open the web application in regular browser, and open DevTools, do you see `window.__coverage__` object? Can you paste a screenshot?
- **Nope, its `undefined` for component tests. Prints the proper obj for normal**
- Is there `.nyc_output` folder? Is there `.nyc_output/out.json` file. Is it empty? Can you paste at least part of it so we can see the keys and file paths?
- **Not generated for component tests**
- Do you have any custom NYC settings in `package.json` (`nyc` object) or in other [NYC config files](https://github.com/istanbuljs/nyc#configuration-files)
- ```    all: true,
    'check-coverage': true,
    reporter: ['html', 'lcov'],
    include: [...],
    exclude: [...],
    branches: ...,
    lines: ...,
    functions: ...,
    statements: ...,```
- Do you run Cypress tests in a Docker container?
- **Yes, but the issue happens outside too**

**Describe the bug**
The code coverage does not work for component testing in v10 without Babel. When I run e2e tests the coverage shows fine. We cannot use babel due to issues outside my reach. I've tried following your tutorials on the [browserify approach](https://github.com/cypress-io/code-coverage#alternative-for-unit-tests) but it didn't give way. It looks like more of a lack-of edge case feature than something we could correct with config.

**Comment by ghsouza89** [comment]
Facing the same issue.

`"cypress": "^12.3.0"`

what I did:

1: Installed code-coverage

- yarn add -D @cypress/code-coverage

2: add to cypress/support/index.js file

- import '@cypress/code-coverage/support'

3: add to cypress/plugins/index.js file
```
module.exports = (on, config) => {
  require('@cypress/code-coverage/task')(on, config)
  return config
}
```


![image](https://user-images.githubusercontent.com/104024271/229954890-9c0067be-5765-4594-817f-b6f2ff4c578c.png)

**Comment by MykSto** [comment]
Also does not work with version 12 with babel

**Comment by majkel89** [comment]
For the moment the workaround I applied was to downgrade cypress to 9.7.0

**Comment by youngsun4786** [comment]
Has anyone fixed it without using `react-script`?

**Comment by mike-plummer** [comment]
While Babel is definitely the easiest way to instrument your code it is not required for `@cypress/code-coverage` to work. A commonly-overlooked aspect of this plugin is that it [does not instrument your code for you](https://www.npmjs.com/package/@cypress/code-coverage#Instrument-your-application) - that is your responsibility; Babel is just a convenient way to hook a tool like `istanbul` into the build process to generate instrumentation. However, it can be done manually by using [`nyc`](https://www.npmjs.com/package/nyc) via command line, using something like `istanbul-instrumenter-loader` as a [Webpack Config customization](https://docs.cypress.io/guides/component-testing/react/overview#Webpack-Configuration) in your component testing config (or a corresponding [Vite customization](https://docs.cypress.io/guides/component-testing/react/overview#Vite-Configuration) with `vite-plugin-istanbul`), or via an alternate compiler like SWC([example](https://github.com/mike-plummer/nextjs-cypress-ct-example#coverage)) as well, it's just a bit trickier.

I would recommend reaching out on [Discord](https://on.cypress.io/discord) as there is likely someone else who has already tackled the same scenario. The majority of public examples do utilize Babel since it's the easiest way (by far!) but the tools linked above are all viable alternatives. As an aside for those asking, [here is an example](https://dev.to/muratkeremozcan/triple-combined-coverage-with-typescript-1dgc) of getting code coverage working on e2e + CT on a CRA project using Typescript.

If anyone has a reproducible example of code coverage not working after after ensuring this plugin is configured properly and their code is being correctly instrumented we would be happy to troubleshoot. As-is, this does not appear to be either a defect or a feature request so I am going to close. Please comment with additional information and reproducible example if you disagree and feel this should remain open
